export const NCM_DATA = [
  { code: "1", description: "Instalações", fiscalYears: 10, fiscalRate: 10 },
  { code: "2", description: "Edificações", fiscalYears: 25, fiscalRate: 4 },
  { code: "3", description: "Equipamentos de informática", fiscalYears: 5, fiscalRate: 20 },
  { code: "101", description: "Animais vivos das espécies cavalar, asinina e muar", fiscalYears: 5, fiscalRate: 20 },
  { code: "102", description: "Animais vivos da espécie bovina", fiscalYears: 5, fiscalRate: 20 },
  { code: "103", description: "Animais vivos da espécie suína", fiscalYears: 5, fiscalRate: 20 },
  { code: "104", description: "Animais vivos das espécies ovina e caprina", fiscalYears: 5, fiscalRate: 20 },
  { code: "105", description: "Galos, galinhas, patos, gansos, perus, peruas e galinhas-d'angola", fiscalYears: 2, fiscalRate: 50 },
  { code: "3923.10", description: "Caixas, caixotes, engradados e artigos semelhantes", fiscalYears: 5, fiscalRate: 20 },
  { code: "3923.30", description: "Garrafões, garrafas, frascos e artigos semelhantes", fiscalYears: 5, fiscalRate: 20 },
  { code: "3923.90", description: "Outros vasilhames", fiscalYears: 5, fiscalRate: 20 },
  { code: "3926.90", description: "Correias de transmissão e correias transportadoras", fiscalYears: 2, fiscalRate: 50 },
  { code: "3926.90A", description: "Artigos de laboratório ou de farmácia", fiscalYears: 5, fiscalRate: 20 },
  { code: "4010", description: "Correias transportadoras ou de transmissão, de borracha vulcanizada", fiscalYears: 2, fiscalRate: 50 },
  { code: "4204", description: "Correias transportadoras ou correias de transmissão", fiscalYears: 2, fiscalRate: 50 },
  { code: "4415", description: "Caixotes, caixas, engradados, barricas e embalagens semelhantes, de madeira", fiscalYears: 5, fiscalRate: 20 },
  { code: "4416", description: "Barris, cubas, balsas, dornas, selhas e outras obras de tanoeiro", fiscalYears: 5, fiscalRate: 20 },
  { code: "5705", description: "Tapetes e outros revestimentos para pavimentos, de matérias têxteis", fiscalYears: 5, fiscalRate: 20 },
  { code: "5910.00", description: "Correias transportadoras ou de transmissão, de matérias têxteis", fiscalYears: 2, fiscalRate: 50 },
  { code: "6303", description: "Cortinados, cortinas e estores; sanefas e artigos semelhantes", fiscalYears: 5, fiscalRate: 20 },
  { code: "6305", description: "Sacos de quaisquer dimensões, para embalagem", fiscalYears: 5, fiscalRate: 20 },
  { code: "6306", description: "Encerados e toldos; tendas; velas para embarcações", fiscalYears: 4, fiscalRate: 25 },
  { code: "6909", description: "Aparelhos e artefatos para usos químicos ou para outros usos técnicos", fiscalYears: 5, fiscalRate: 20 },
  { code: "7010", description: "Garrafões, garrafas, frascos, boiões, vasos, embalagens tubulares", fiscalYears: 5, fiscalRate: 20 },
  { code: "7308.10", description: "Pontes e elementos de pontes", fiscalYears: 25, fiscalRate: 4 },
  { code: "7308.20", description: "Torres e pórticos", fiscalYears: 25, fiscalRate: 4 },
  { code: "7309", description: "Reservatórios, tonéis, cubas e recipientes semelhantes", fiscalYears: 10, fiscalRate: 10 },
  { code: "7311", description: "Recipientes para gases comprimidos ou liquefeitos", fiscalYears: 5, fiscalRate: 20 },
  { code: "7321", description: "Aquecedores de ambientes (fogões de sala), caldeiras de fornalha", fiscalYears: 10, fiscalRate: 10 },
  { code: "7322", description: "Radiadores para aquecimento central, não elétricos", fiscalYears: 10, fiscalRate: 10 },
  { code: "7610", description: "Construções de alumínio", fiscalYears: 25, fiscalRate: 4 },
  { code: "7611", description: "Reservatórios, tonéis, cubas e recipientes semelhantes (Alumínio)", fiscalYears: 10, fiscalRate: 10 },
  { code: "7613", description: "Recipientes para gases comprimidos ou liquefeitos (Alumínio)", fiscalYears: 5, fiscalRate: 20 },
  { code: "8201", description: "Pás, alviões, picaretas, enxadas, sachos, forcados", fiscalYears: 5, fiscalRate: 20 },
  { code: "8202", description: "Serras manuais; folhas de serras de todos os tipos", fiscalYears: 5, fiscalRate: 20 },
  { code: "8203.20", description: "Alicates (mesmo cortantes), tenazes, pinças", fiscalYears: 5, fiscalRate: 20 },
  { code: "8203.30", description: "Cisalhas para metais e ferramentas semelhantes", fiscalYears: 5, fiscalRate: 20 },
  { code: "8203.40", description: "Corta-tubos, corta-pinos, saca-bocados", fiscalYears: 5, fiscalRate: 20 },
  { code: "8204", description: "Chaves de porcas, manuais; chaves de caixa intercambiáveis", fiscalYears: 5, fiscalRate: 20 },
  { code: "8205", description: "Ferramentas manuais (incluídos os corta-vidros)", fiscalYears: 5, fiscalRate: 20 },
  { code: "8206", description: "Ferramentas de pelo menos duas das posições 8202 a 8205", fiscalYears: 5, fiscalRate: 20 },
  { code: "8207.30", description: "Ferramentas de embutir, de estampar ou de puncionar", fiscalYears: 5, fiscalRate: 20 },
  { code: "8210", description: "Aparelhos mecânicos de acionamento manual (preparar alimentos)", fiscalYears: 10, fiscalRate: 10 },
  { code: "8214", description: "Máquinas de tosquiar", fiscalYears: 5, fiscalRate: 20 },
  { code: "8303", description: "Cofres-fortes, portas blindadas e compartimentos para casas-fortes", fiscalYears: 10, fiscalRate: 10 },
  { code: "8304", description: "Classificadores, fichários, caixas de classificação", fiscalYears: 10, fiscalRate: 10 },
  { code: "8401", description: "Reatores nucleares; elementos combustíveis (cartuchos)", fiscalYears: 10, fiscalRate: 10 },
  { code: "8402", description: "Caldeiras de vapor (geradores de vapor)", fiscalYears: 10, fiscalRate: 10 },
  { code: "8403", description: "Caldeiras para aquecimento central", fiscalYears: 10, fiscalRate: 10 },
  { code: "8404", description: "Aparelhos auxiliares para caldeiras", fiscalYears: 10, fiscalRate: 10 },
  { code: "8405", description: "Geradores de gás de ar (gás pobre) ou de gás de água", fiscalYears: 10, fiscalRate: 10 },
  { code: "8406", description: "Turbinas a vapor", fiscalYears: 10, fiscalRate: 10 },
  { code: "8407", description: "Motores de pistão, alternativo ou rotativo (explosão)", fiscalYears: 10, fiscalRate: 10 },
  { code: "8408", description: "Motores de pistão, de ignição por compressão (diesel)", fiscalYears: 10, fiscalRate: 10 },
  { code: "8410", description: "Turbinas hidráulicas, rodas hidráulicas, e seus reguladores", fiscalYears: 10, fiscalRate: 10 },
  { code: "8411", description: "Turborreatores, turbopropulsores e outras turbinas a gás", fiscalYears: 10, fiscalRate: 10 },
  { code: "8412", description: "Outros motores e máquinas motrizes", fiscalYears: 10, fiscalRate: 10 },
  { code: "8413", description: "Bombas para líquidos, mesmo com dispositivo medidor", fiscalYears: 10, fiscalRate: 10 },
  { code: "8414", description: "Bombas de ar ou de vácuo, compressores de ar", fiscalYears: 10, fiscalRate: 10 },
  { code: "8415", description: "Máquinas e aparelhos de ar-condicionado", fiscalYears: 10, fiscalRate: 10 },
  { code: "8416", description: "Queimadores para alimentação de fornalhas", fiscalYears: 10, fiscalRate: 10 },
  { code: "8417", description: "Fornos industriais ou de laboratório, não elétricos", fiscalYears: 10, fiscalRate: 10 },
  { code: "8418", description: "Refrigeradores, congeladores (freezers)", fiscalYears: 10, fiscalRate: 10 },
  { code: "8419", description: "Aparelhos e dispositivos para tratamento de matérias", fiscalYears: 10, fiscalRate: 10 },
  { code: "8420", description: "Calandras e laminadores", fiscalYears: 10, fiscalRate: 10 },
  { code: "8421", description: "Centrifugadores, incluídos os secadores centrífugos", fiscalYears: 10, fiscalRate: 10 },
  { code: "8422", description: "Máquinas de lavar louça; máquinas para limpar garrafas", fiscalYears: 10, fiscalRate: 10 },
  { code: "8423", description: "Aparelhos e instrumentos de pesagem", fiscalYears: 10, fiscalRate: 10 },
  { code: "8424", description: "Aparelhos mecânicos para projetar, dispersar ou pulverizar", fiscalYears: 10, fiscalRate: 10 },
  { code: "8425", description: "Talhas, cadernais e moitões; guinchos e cabrestantes", fiscalYears: 10, fiscalRate: 10 },
  { code: "8426", description: "Cábreas; guindastes, incluídos os de cabo", fiscalYears: 10, fiscalRate: 10 },
  { code: "8427", description: "Empilhadeiras; outros veículos para movimentação de carga", fiscalYears: 10, fiscalRate: 10 },
  { code: "8428", description: "Outras máquinas e aparelhos de elevação, de carga", fiscalYears: 10, fiscalRate: 10 },
  { code: "8429", description: "Bulldozers, angledozers, niveladores", fiscalYears: 4, fiscalRate: 25 },
  { code: "8430", description: "Outras máquinas e aparelhos de terraplenagem", fiscalYears: 10, fiscalRate: 10 },
  { code: "8432", description: "Máquinas e aparelhos de uso agrícola, hortícola ou florestal", fiscalYears: 10, fiscalRate: 10 },
  { code: "8433", description: "Máquinas e aparelhos para colheita ou debulha", fiscalYears: 10, fiscalRate: 10 },
  { code: "8434", description: "Máquinas de ordenhar e máquinas para indústria de laticínios", fiscalYears: 10, fiscalRate: 10 },
  { code: "8435", description: "Prensas, esmagadores e máquinas semelhantes", fiscalYears: 10, fiscalRate: 10 },
  { code: "8436", description: "Outras máquinas e aparelhos para agricultura", fiscalYears: 10, fiscalRate: 10 },
  { code: "8437", description: "Máquinas para limpeza, seleção ou peneiração de grãos", fiscalYears: 10, fiscalRate: 10 },
  { code: "8438", description: "Máquinas e aparelhos para preparação industrial de alimentos", fiscalYears: 10, fiscalRate: 10 },
  { code: "8439", description: "Máquinas e aparelhos para fabricação de pasta de matérias fibrosas", fiscalYears: 10, fiscalRate: 10 },
  { code: "8440", description: "Máquinas e aparelhos para brochura ou encadernação", fiscalYears: 10, fiscalRate: 10 },
  { code: "8441", description: "Outras máquinas e aparelhos para o trabalho da pasta de papel", fiscalYears: 10, fiscalRate: 10 },
  { code: "8442", description: "Máquinas, aparelhos e material para fundir ou compor caracteres", fiscalYears: 10, fiscalRate: 10 },
  { code: "8443", description: "Máquinas e aparelhos de impressão", fiscalYears: 10, fiscalRate: 10 },
  { code: "8444", description: "Máquinas para extrudar, estirar, texturizar ou cortar", fiscalYears: 10, fiscalRate: 10 },
  { code: "8445", description: "Máquinas para preparação de matérias têxteis", fiscalYears: 10, fiscalRate: 10 },
  { code: "8446", description: "Teares para tecidos", fiscalYears: 10, fiscalRate: 10 },
  { code: "8447", description: "Teares para fabricar malhas, máquinas de costura", fiscalYears: 10, fiscalRate: 10 },
  { code: "8448", description: "Máquinas e aparelhos auxiliares para as máquinas das posições 8444 a 8447", fiscalYears: 10, fiscalRate: 10 },
  { code: "8449", description: "Máquinas e aparelhos para fabricação ou acabamento de feltro", fiscalYears: 10, fiscalRate: 10 },
  { code: "8450", description: "Máquinas de lavar roupa, mesmo com dispositivos de secagem", fiscalYears: 10, fiscalRate: 10 },
  { code: "8451", description: "Máquinas e aparelhos para lavar, limpar, espremer, secar", fiscalYears: 10, fiscalRate: 10 },
  { code: "8452", description: "Máquinas de costura, exceto as de costurar cadernos", fiscalYears: 10, fiscalRate: 10 },
  { code: "8453", description: "Máquinas e aparelhos para preparar, curtir ou trabalhar couros", fiscalYears: 10, fiscalRate: 10 },
  { code: "8454", description: "Conversores, cadinhos ou colheres de fundição", fiscalYears: 10, fiscalRate: 10 },
  { code: "8455", description: "Laminadores de metais e seus cilindros", fiscalYears: 10, fiscalRate: 10 },
  { code: "8456", description: "Máquinas-ferramentas que trabalhem por eliminação de matéria", fiscalYears: 10, fiscalRate: 10 },
  { code: "8457", description: "Centros de usinagem, máquinas de sistema monostático", fiscalYears: 10, fiscalRate: 10 },
  { code: "8458", description: "Tornos (incluídos os centros de torneamento) para metais", fiscalYears: 10, fiscalRate: 10 },
  { code: "8459", description: "Máquinas-ferramentas para furar, mandrilar, fresar", fiscalYears: 10, fiscalRate: 10 },
  { code: "8460", description: "Máquinas-ferramentas para rebarbar, afiar, amolar", fiscalYears: 10, fiscalRate: 10 },
  { code: "8461", description: "Máquinas-ferramentas para aplainar, plainaslimadoras", fiscalYears: 10, fiscalRate: 10 },
  { code: "8462", description: "Máquinas-ferramentas (incluídas as prensas) para forjar", fiscalYears: 10, fiscalRate: 10 },
  { code: "8463", description: "Outras máquinas-ferramentas para trabalhar metais", fiscalYears: 10, fiscalRate: 10 },
  { code: "8464", description: "Máquinas-ferramentas para trabalhar pedra, concreto", fiscalYears: 10, fiscalRate: 10 },
  { code: "8465", description: "Máquinas-ferramentas para trabalhar madeira, cortiça", fiscalYears: 10, fiscalRate: 10 },
  { code: "8467", description: "Ferramentas pneumáticas, hidráulicas ou de motor", fiscalYears: 10, fiscalRate: 10 },
  { code: "8468", description: "Máquinas e aparelhos para soldar", fiscalYears: 10, fiscalRate: 10 },
  { code: "8469", description: "Máquinas de escrever; máquinas de tratamento de textos", fiscalYears: 10, fiscalRate: 10 },
  { code: "8470.21", description: "Máquinas eletrônicas de calcular com impressor", fiscalYears: 10, fiscalRate: 10 },
  { code: "8470.29", description: "Outras máquinas eletrônicas de calcular", fiscalYears: 10, fiscalRate: 10 },
  { code: "8470.30", description: "Outras máquinas de calcular", fiscalYears: 10, fiscalRate: 10 },
  { code: "8470.40", description: "Máquinas de contabilidade", fiscalYears: 10, fiscalRate: 10 },
  { code: "8470.50", description: "Caixas registradoras", fiscalYears: 10, fiscalRate: 10 },
  { code: "8470.90", description: "Máquinas de franquear correspondência", fiscalYears: 10, fiscalRate: 10 },
  { code: "8471", description: "Máquinas automáticas para processamento de dados", fiscalYears: 5, fiscalRate: 20 },
  { code: "8472", description: "Outras máquinas e aparelhos de escritório", fiscalYears: 10, fiscalRate: 10 },
  { code: "8474", description: "Máquinas e aparelhos para selecionar, peneirar, separar", fiscalYears: 5, fiscalRate: 20 },
  { code: "8475", description: "Máquinas para montagem de lâmpadas, tubos ou válvulas", fiscalYears: 10, fiscalRate: 10 },
  { code: "8476", description: "Máquinas automáticas de venda de produtos", fiscalYears: 10, fiscalRate: 10 },
  { code: "8477", description: "Máquinas e aparelhos para trabalhar borracha ou plásticos", fiscalYears: 10, fiscalRate: 10 },
  { code: "8478", description: "Máquinas e aparelhos para preparar ou transformar fumo", fiscalYears: 10, fiscalRate: 10 },
  { code: "8479.10", description: "Máquinas e aparelhos para obras públicas", fiscalYears: 4, fiscalRate: 25 },
  { code: "8479.20", description: "Máquinas e aparelhos para extração de óleos", fiscalYears: 10, fiscalRate: 10 },
  { code: "8479.30", description: "Prensas para fabricação de painéis de partículas", fiscalYears: 10, fiscalRate: 10 },
  { code: "8479.40", description: "Máquinas para fabricação de cordas ou cabos", fiscalYears: 10, fiscalRate: 10 },
  { code: "8479.50", description: "Robôs industriais, não especificados", fiscalYears: 10, fiscalRate: 10 },
  { code: "8479.60", description: "Aparelhos de evaporação para arrefecimento do ar", fiscalYears: 10, fiscalRate: 10 },
  { code: "8479.81", description: "Para tratamento de metais", fiscalYears: 10, fiscalRate: 10 },
  { code: "8479.82", description: "Para misturar, amassar, esmagar, moer", fiscalYears: 10, fiscalRate: 10 },
  { code: "8479.89", description: "Outros aparelhos mecânicos", fiscalYears: 10, fiscalRate: 10 },
  { code: "8480", description: "Caixas de fundição; placas de fundo para moldes", fiscalYears: 3, fiscalRate: 33 },
  { code: "8483.40", description: "Caixas de transmissão, redutores, multiplicadores", fiscalYears: 10, fiscalRate: 10 },
  { code: "8501", description: "Motores e geradores, elétricos", fiscalYears: 10, fiscalRate: 10 },
  { code: "8502", description: "Grupos eletrogêneos e conversores rotativos", fiscalYears: 10, fiscalRate: 10 },
  { code: "8504", description: "Transformadores elétricos, conversores estáticos", fiscalYears: 10, fiscalRate: 10 },
  { code: "8508", description: "Ferramentas eletromecânicas de motor elétrico", fiscalYears: 5, fiscalRate: 20 },
  { code: "8510", description: "Aparelhos ou máquinas de tosquiar", fiscalYears: 5, fiscalRate: 20 },
  { code: "8514", description: "Fornos elétricos industriais ou de laboratório", fiscalYears: 10, fiscalRate: 10 },
  { code: "8515", description: "Máquinas e aparelhos para soldar elétricos", fiscalYears: 10, fiscalRate: 10 },
  { code: "8516", description: "Aparelhos elétricos para aquecimento de ambientes", fiscalYears: 10, fiscalRate: 10 },
  { code: "8517", description: "Aparelhos elétricos para telefonia ou telegrafia", fiscalYears: 5, fiscalRate: 20 },
  { code: "8520", description: "Gravadores de dados de voo", fiscalYears: 5, fiscalRate: 20 },
  { code: "8521.10", description: "Gravador-reprodutor de fita magnética", fiscalYears: 5, fiscalRate: 20 },
  { code: "8521.90", description: "Gravador-reprodutor e editor de imagem e som", fiscalYears: 5, fiscalRate: 20 },
  { code: "8524.3", description: "Discos para sistemas de leitura por raio laser", fiscalYears: 3, fiscalRate: 33 },
  { code: "8524.40", description: "Fitas magnéticas para reprodução de fenômenos", fiscalYears: 3, fiscalRate: 33 },
  { code: "8524.5", description: "Outras fitas magnéticas", fiscalYears: 3, fiscalRate: 33 },
  { code: "8524.60", description: "Cartões magnéticos", fiscalYears: 3, fiscalRate: 33 },
  { code: "8525", description: "Aparelhos transmissores para radiotelefonia", fiscalYears: 5, fiscalRate: 20 },
  { code: "8526", description: "Aparelhos de radiodetecção e de radiossondagem", fiscalYears: 5, fiscalRate: 20 },
  { code: "8527", description: "Aparelhos receptores para radiotelefonia", fiscalYears: 5, fiscalRate: 20 },
  { code: "8531.20", description: "Painéis indicadores com cristais líquidos (LCD)", fiscalYears: 5, fiscalRate: 20 },
  { code: "8543", description: "Máquinas e aparelhos elétricos com função própria", fiscalYears: 10, fiscalRate: 10 },
  { code: "8601", description: "Locomotivas e locotratores elétricos", fiscalYears: 10, fiscalRate: 10 },
  { code: "8602", description: "Outras locomotivas e locotratores; tênderes", fiscalYears: 10, fiscalRate: 10 },
  { code: "8603", description: "Litorinas (automotoras)", fiscalYears: 10, fiscalRate: 10 },
  { code: "8604", description: "Veículos para inspeção e manutenção de vias férreas", fiscalYears: 10, fiscalRate: 10 },
  { code: "8605", description: "Vagões de passageiros, furgões para bagagem", fiscalYears: 10, fiscalRate: 10 },
  { code: "8606", description: "Vagões para transporte de mercadorias", fiscalYears: 10, fiscalRate: 10 },
  { code: "8608", description: "Aparelhos mecânicos de sinalização", fiscalYears: 10, fiscalRate: 10 },
  { code: "8609", description: "Conteineres (contentores)", fiscalYears: 10, fiscalRate: 10 },
  { code: "8701", description: "Tratores (exceto carros-tratores)", fiscalYears: 4, fiscalRate: 25 },
  { code: "8702", description: "Veículos automóveis para transporte de 10 pessoas", fiscalYears: 4, fiscalRate: 25 },
  { code: "8703", description: "Automóveis de passageiros", fiscalYears: 5, fiscalRate: 20 },
  { code: "8704", description: "Veículos automóveis para transporte de mercadorias", fiscalYears: 4, fiscalRate: 25 },
  { code: "8705", description: "Veículos automóveis para usos especiais", fiscalYears: 4, fiscalRate: 25 },
  { code: "8709", description: "Veículos automóveis sem dispositivo de elevação", fiscalYears: 10, fiscalRate: 10 },
  { code: "8711", description: "Motocicletas (incluídos os ciclomotores)", fiscalYears: 4, fiscalRate: 25 },
  { code: "8716", description: "Reboques e semi-reboques", fiscalYears: 5, fiscalRate: 20 },
  { code: "8801", description: "Balões e dirigíveis; planadores", fiscalYears: 10, fiscalRate: 10 },
  { code: "8802", description: "Outros veículos aéreos (helicópteros, aviões)", fiscalYears: 10, fiscalRate: 10 },
  { code: "8804", description: "Pára-quedas e os pára-quedas giratórios", fiscalYears: 10, fiscalRate: 10 },
  { code: "8805", description: "Aparelhos e dispositivos para lançamento", fiscalYears: 10, fiscalRate: 10 },
  { code: "8901", description: "Transatlânticos, barcos de cruzeiro, ferry-boats", fiscalYears: 20, fiscalRate: 5 },
  { code: "8902", description: "Barcos de pesca; navios-fábricas", fiscalYears: 20, fiscalRate: 5 },
  { code: "8903.10", description: "Barcos infláveis", fiscalYears: 5, fiscalRate: 20 },
  { code: "8903.9", description: "Outros barcos", fiscalYears: 10, fiscalRate: 10 },
  { code: "8904", description: "Rebocadores e barcos concebidos para empurrar", fiscalYears: 20, fiscalRate: 5 },
  { code: "8906", description: "Outras embarcações, incluídos os navios de guerra", fiscalYears: 20, fiscalRate: 5 },
  { code: "8907.10", description: "Balsas infláveis", fiscalYears: 5, fiscalRate: 20 },
  { code: "8907.90", description: "Outras embarcações flutuantes", fiscalYears: 20, fiscalRate: 5 },
  { code: "9005", description: "Binóculos, lunetas, telescópios ópticos", fiscalYears: 10, fiscalRate: 10 },
  { code: "9006", description: "Aparelhos fotográficos", fiscalYears: 10, fiscalRate: 10 },
  { code: "9007", description: "Câmeras e projetores cinematográficos", fiscalYears: 10, fiscalRate: 10 },
  { code: "9008", description: "Aparelhos de projeção fixa", fiscalYears: 10, fiscalRate: 10 },
  { code: "9009", description: "Aparelhos de fotocópia e de termocópia", fiscalYears: 10, fiscalRate: 10 },
  { code: "9010", description: "Aparelhos usados nos laboratórios fotográficos", fiscalYears: 10, fiscalRate: 10 },
  { code: "9011", description: "Microscópios ópticos", fiscalYears: 10, fiscalRate: 10 },
  { code: "9012", description: "Microscópios (exceto ópticos) e difratógrafos", fiscalYears: 10, fiscalRate: 10 },
  { code: "9014", description: "Bússolas; outros instrumentos de navegação", fiscalYears: 10, fiscalRate: 10 },
  { code: "9015", description: "Instrumentos e aparelhos de geodésia", fiscalYears: 10, fiscalRate: 10 },
  { code: "9016", description: "Balanças sensíveis a pesos iguais ou inferiores a 5cg", fiscalYears: 10, fiscalRate: 10 },
  { code: "9017", description: "Instrumentos de desenho, de traçado ou de cálculo", fiscalYears: 10, fiscalRate: 10 },
  { code: "9018.1", description: "Aparelhos de eletrodiagnóstico", fiscalYears: 10, fiscalRate: 10 },
  { code: "9018.20", description: "Aparelhos de raios ultravioleta ou infravermelhos", fiscalYears: 10, fiscalRate: 10 },
  { code: "9018.41", description: "Aparelhos dentários de brocar", fiscalYears: 10, fiscalRate: 10 },
  { code: "9018.49", description: "Outros instrumentos e aparelhos para odontologia", fiscalYears: 10, fiscalRate: 10 },
  { code: "9018.50", description: "Outros instrumentos e aparelhos para oftalmologia", fiscalYears: 10, fiscalRate: 10 },
  { code: "9018.90", description: "Outros instrumentos e aparelhos médicos", fiscalYears: 10, fiscalRate: 10 },
  { code: "9019", description: "Aparelhos de mecanoterapia; aparelhos de massagem", fiscalYears: 10, fiscalRate: 10 },
  { code: "9020", description: "Outros aparelhos respiratórios e máscaras", fiscalYears: 10, fiscalRate: 10 },
  { code: "9022", description: "Aparelhos de raios X e aparelhos que utilizem radiações", fiscalYears: 10, fiscalRate: 10 },
  { code: "9024", description: "Máquinas e aparelhos para ensaios de dureza", fiscalYears: 10, fiscalRate: 10 },
  { code: "9025", description: "Densímetros, areômetros, termômetros", fiscalYears: 10, fiscalRate: 10 },
  { code: "9026", description: "Instrumentos para medida ou controle da vazão", fiscalYears: 10, fiscalRate: 10 },
  { code: "9027", description: "Instrumentos e aparelhos para análises físicas", fiscalYears: 10, fiscalRate: 10 },
  { code: "9028", description: "Contadores de gases, líquidos ou de eletricidade", fiscalYears: 10, fiscalRate: 10 },
  { code: "9029", description: "Outros contadores; indicadores de velocidade", fiscalYears: 10, fiscalRate: 10 },
  { code: "9030", description: "Osciloscópios, analisadores de espectro", fiscalYears: 10, fiscalRate: 10 },
  { code: "9031", description: "Instrumentos, aparelhos e máquinas de medida", fiscalYears: 10, fiscalRate: 10 },
  { code: "9032", description: "Instrumentos e aparelhos para regulação automática", fiscalYears: 10, fiscalRate: 10 },
  { code: "9402", description: "Mobiliário para medicina, cirurgia, odontologia", fiscalYears: 10, fiscalRate: 10 },
  { code: "9403", description: "Outros móveis para escritório", fiscalYears: 10, fiscalRate: 10 },
  { code: "9406", description: "Construções pré-fabricadas", fiscalYears: 25, fiscalRate: 4 },
  { code: "9506", description: "Artigos e equipamentos para cultura física", fiscalYears: 10, fiscalRate: 10 },
  { code: "9508", description: "Carrosséis, balanços, instalações de tiro-ao-alvo", fiscalYears: 10, fiscalRate: 10 },
];

export const COST_CENTERS = [
  { code: "10", description: "Administrativo" },
  { code: "20", description: "Financeiro" },
  { code: "30", description: "TI - Infraestrutura" },
  { code: "40", description: "Comercial" },
  { code: "50", description: "Logística" },
  { code: "60", description: "Produção" },
  { code: "70", description: "Manutenção" },
];

export const ACCOUNTS = [
  { code: "100000", description: "Terrenos", class: "10" },
  { code: "100001", description: "Edificações", class: "20" },
  { code: "100002", description: "Instalações", class: "1" },
  { code: "100003", description: "Equipamentos", class: "50" },
  { code: "100004", description: "Hardware", class: "80" },
  { code: "100005", description: "Veículos", class: "90" },
  { code: "100006", description: "Móveis e Utensílios", class: "70" },
  { code: "110001", description: "(-) Depreciação - Edificações", class: "20" },
  { code: "110002", description: "(-) Depreciação - Instalações", class: "1" },
  { code: "110003", description: "(-) Depreciação - Equipamentos", class: "50" },
  { code: "110004", description: "(-) Depreciação - Hardware", class: "80" },
  { code: "110005", description: "(-) Depreciação - Veículos", class: "90" },
  { code: "110006", description: "(-) Depreciação - Móveis e Utensílios", class: "70" },
];

export const CLASSES = [
  { code: "10", description: "Terrenos" },
  { code: "20", description: "Edificações" },
  { code: "50", description: "Equipamentos" },
  { code: "80", description: "Hardware" },
  { code: "90", description: "Veículos" },
  { code: "70", description: "Móveis e Utensílios" },
];

export const DEFAULT_FIELD_CONFIG = [
  // Dados Gerais
  { id: 'name', label: 'Denominação', visible: true, collectorVisible: true, category: 'gerais' },
  { id: 'brand', label: 'Marca', visible: true, collectorVisible: true, category: 'gerais' },
  { id: 'model', label: 'Modelo', visible: true, collectorVisible: true, category: 'gerais' },
  { id: 'licensePlate', label: 'Placa de Veículo', visible: true, collectorVisible: false, category: 'gerais' },
  { id: 'serialNumber', label: 'Nº Série', visible: true, collectorVisible: true, category: 'gerais' },
  { id: 'chassis', label: 'Chassi', visible: true, collectorVisible: false, category: 'gerais' },
  { id: 'engine', label: 'Motor', visible: true, collectorVisible: false, category: 'gerais' },
  { id: 'rpm', label: 'RPM', visible: true, collectorVisible: false, category: 'gerais' },
  { id: 'dimensions', label: 'Tamanho/Dimensão', visible: true, collectorVisible: false, category: 'gerais' },
  { id: 'tag', label: 'TAG', visible: true, collectorVisible: false, category: 'gerais' },
  { id: 'equipmentNumber', label: 'Nº Equipamento', visible: true, collectorVisible: false, category: 'gerais' },
  { id: 'unit', label: 'Unidade Medida', visible: true, collectorVisible: false, category: 'gerais' },
  { id: 'capacity', label: 'Capacidade/Peso', visible: true, collectorVisible: false, category: 'gerais' },
  { id: 'color', label: 'Cor', visible: true, collectorVisible: false, category: 'gerais' },
  
  // Financeiro
  { id: 'acquisitionDate', label: 'Data Aquisição', visible: true, collectorVisible: false, category: 'financeiro' },
  { id: 'incorporationDate', label: 'Data Incorporação', visible: true, collectorVisible: false, category: 'financeiro' },
  { id: 'acquisitionValueBRL', label: 'Valor Aquisição (BRL)', visible: true, collectorVisible: false, category: 'financeiro' },
  { id: 'residualValueBRL', label: 'Valor Residual (BRL)', visible: true, collectorVisible: false, category: 'financeiro' },
  { id: 'acquisitionValueUSD', label: 'Valor Aquisição (USD)', visible: true, collectorVisible: false, category: 'financeiro' },
  { id: 'residualValueUSD', label: 'Valor Residual (USD)', visible: true, collectorVisible: false, category: 'financeiro' },
  
  // Localização
  { id: 'companyId', label: 'Empresa', visible: true, collectorVisible: false, category: 'localizacao' },
  { id: 'branchId', label: 'Filial', visible: true, collectorVisible: false, category: 'localizacao' },
  { id: 'accountCode', label: 'Conta Contábil', visible: true, collectorVisible: false, category: 'localizacao' },
  { id: 'previousAccount', label: 'Conta Anterior', visible: true, collectorVisible: false, category: 'localizacao' },
  { id: 'classCode', label: 'Classe', visible: true, collectorVisible: false, category: 'localizacao' },
  { id: 'previousClass', label: 'Classe Anterior', visible: true, collectorVisible: false, category: 'localizacao' },
  { id: 'costCenterCode', label: 'Centro de Custo', visible: true, collectorVisible: true, category: 'localizacao' },
  { id: 'previousCostCenter', label: 'C. Custo Anterior', visible: true, collectorVisible: false, category: 'localizacao' },
  { id: 'location', label: 'Localização', visible: true, collectorVisible: true, category: 'localizacao' },
  { id: 'room', label: 'Sala', visible: true, collectorVisible: false, category: 'localizacao' },
  { id: 'environment', label: 'Ambiente', visible: true, collectorVisible: false, category: 'localizacao' },
  { id: 'collaborator', label: 'Colaborador', visible: true, collectorVisible: false, category: 'localizacao' },
  { id: 'responsible', label: 'Responsável', visible: true, collectorVisible: false, category: 'localizacao' },
  { id: 'condition', label: 'Condição de Uso', visible: true, collectorVisible: false, category: 'localizacao' },
  { id: 'observations', label: 'Observações', visible: true, collectorVisible: false, category: 'localizacao' },
  
  // Fiscal
  { id: 'nfe', label: 'NF-e', visible: true, category: 'fiscal' },
  { id: 'nfeKey', label: 'Chave NF-e', visible: true, category: 'fiscal' },
  { id: 'nfeAttachment', label: 'Anexo NF-e', visible: true, category: 'fiscal' },
  { id: 'incentive_incentivosCreditos', label: 'Incentivos / Créditos fiscais', visible: true, category: 'fiscal' },
  { id: 'incentive_ciap', label: 'CIAP', visible: true, category: 'fiscal' },
  { id: 'incentive_depIncentivada', label: 'Depreciação incentivada', visible: true, category: 'fiscal' },
  { id: 'incentive_depCSLL', label: 'Depreciação CSLL', visible: true, category: 'fiscal' },
  { id: 'incentive_depAcelerada', label: 'Depreciação acelerada', visible: true, category: 'fiscal' },
  { id: 'incentive_recap', label: 'RECAP', visible: true, category: 'fiscal' },
  { id: 'incentive_creditoImediato', label: 'Crédito Imediato', visible: true, category: 'fiscal' },
  { id: 'incentive_drawback', label: 'Drawback', visible: true, category: 'fiscal' },
  { id: 'incentive_sudamSudene', label: 'SUDAM / SUDENE', visible: true, category: 'fiscal' },
  { id: 'incentive_zfm', label: 'Zona Franca de Manaus (ZFM)', visible: true, category: 'fiscal' },
  { id: 'incentive_repes', label: 'REPES', visible: true, category: 'fiscal' },
  { id: 'incentive_others', label: 'Outros', visible: true, category: 'fiscal' },
  
  // Vida Útil
  { id: 'ncm', label: 'NCM', visible: true, category: 'vidautil' },
  { id: 'ncmDescription', label: 'Descrição NCM', visible: true, category: 'vidautil' },
  { id: 'fiscalUsefulLifeYears', label: 'Vida Útil Fiscal (Anos)', visible: true, category: 'vidautil' },
  { id: 'fiscalUsefulLifeMonths', label: 'Vida Útil Fiscal (Meses)', visible: true, category: 'vidautil' },
  { id: 'fiscalAnnualRate', label: 'Taxa Anual Fiscal', visible: true, category: 'vidautil' },
  { id: 'accountingUsefulLifeYears', label: 'Vida Útil Contábil (Anos)', visible: true, category: 'vidautil' },
  { id: 'accountingUsefulLifeMonths', label: 'Vida Útil Contábil (Meses)', visible: true, category: 'vidautil' },
  { id: 'accountingAnnualRate', label: 'Taxa Anual Contábil', visible: true, category: 'vidautil' },

  // Outros (Controle de Abas)
  { id: 'tab_fornecedor', label: 'Habilitar Aba Fornecedor', visible: true, category: 'outros' },
  { id: 'tab_seguros', label: 'Habilitar Aba Seguros', visible: true, category: 'outros' },
  { id: 'tab_manutencao', label: 'Habilitar Aba Manutenção', visible: true, category: 'outros' },
  { id: 'tab_leasing', label: 'Habilitar Aba Leasing', visible: true, category: 'outros' },
  { id: 'tab_documentos', label: 'Habilitar Aba DOCUMENTOS', visible: true, category: 'outros' },
  { id: 'tab_etiquetagem', label: 'Habilitar Aba ETIQUETAGEM', visible: true, category: 'outros' },
  { id: 'tab_historico', label: 'Habilitar Aba HISTÓRICO', visible: true, category: 'outros' },
];
